server:
  port: 80
spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:/root/.h2/lab
    username: laopeng
    password: wzx458950
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
  mail:
    host: smtp.qq.com
    default-encoding: UTF-8
    username: 463508232@qq.com
    password: rghhsquibqogcbba
    port: 587
mail:
  from: 463508232@qq.com
security:
  basic:
    enabled: false
logging:
  level:
    root: error